# This is a shared workflow

name: build gem

on:
  workflow_call:
    inputs:
      runs-on:
        description: operating system
        type: string
        required: true
      make-target:
        description: target to compile
        type: string
        required: true
      ruby-platform:
        description: ruby platform to pack
        type: string
        required: true
      gem-version:
        description: gem version
        type: string
        required: true

      artifact1-name:
        description: name of the artifact 1
        type: string
        required: false
        default: ''
      artifact2-name:
        description: name of the artifact 2
        type: string
        required: false
        default: ''
      artifact3-name:
        description: name of the artifact 3
        type: string
        required: false
        default: ''

      artifact1-path:
        description: path of the artifact 1
        type: string
        required: false
        default: ''
      artifact2-path:
        description: path of the artifact 2
        type: string
        required: false
        default: ''
      artifact3-path:
        description: path of the artifact 3
        type: string
        required: false
        default: ''
    outputs:
      gem-artifact-name:
        description: artifact name
        value: ${{ jobs.build-gem.outputs.gem-artifact-name }}

defaults:
  run:
    shell: bash

jobs:
  build-gem:
    name: build gem on ${{ inputs.runs-on }}
    runs-on: ${{ inputs.runs-on }}
    env:
      TARGET: ${{ inputs.make-target }}
      OUTPUT_ARTIFACT_NAME: lib-ruby-parser-${{ inputs.gem-version }}-${{ inputs.ruby-platform }}.gem
    outputs:
      gem-artifact-name: ${{ steps.upload.outputs.gem-artifact-name }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: print inputs
        run: |
          echo "runs-on = ${{ inputs.runs-on }}"
          echo "make-target = ${{ inputs.make-target }}"
          echo "ruby-platform = ${{ inputs.ruby-platform }}"
          echo "gem-version = ${{ inputs.gem-version }}"
          echo "artifact1-name = ${{ inputs.artifact1-name }}"
          echo "artifact2-name = ${{ inputs.artifact2-name }}"
          echo "artifact3-name = ${{ inputs.artifact3-name }}"
          echo "artifact1-path = ${{ inputs.artifact1-path }}"
          echo "artifact2-path = ${{ inputs.artifact2-path }}"
          echo "artifact3-path = ${{ inputs.artifact3-path }}"

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: download artifact 1
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact1-name }}
          path: artifact1
        if: ${{ inputs.artifact1-name != '' }}

      - name: move artifact 1
        run: |
          ls -l artifact1/
          mv artifact1/* ${{ inputs.artifact1-path }}
        if: ${{ inputs.artifact1-name != '' }}

      - name: download artifact 2
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact2-name }}
          path: artifact2
        if: ${{ inputs.artifact2-name != '' }}

      - name: move artifact 2
        run: |
          ls -l artifact2/
          mv artifact2/* ${{ inputs.artifact2-path }}
        if: ${{ inputs.artifact2-name != '' }}

      - name: download artifact 3
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact3-name }}
          path: artifact3
        if: ${{ inputs.artifact3-name != '' }}

      - name: move artifact 3
        run: |
          ls -l artifact3/
          mv artifact3/* ${{ inputs.artifact3-path }}
        if: ${{ inputs.artifact3-name != '' }}

      - name: build .gem file
        run: |
          ls -l
          ls -l lib/lib-ruby-parser/native/
          ls -l lib/lib-ruby-parser/native/2.6/
          ls -l lib/lib-ruby-parser/native/2.7/
          ls -l lib/lib-ruby-parser/native/3.0/
          make build-package

      - name: upload .gem
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.OUTPUT_ARTIFACT_NAME }}
          path: build/${{ env.OUTPUT_ARTIFACT_NAME }}

      - name: output upload name
        id: upload
        run: echo ::set-output name=gem-artifact-name::$OUTPUT_ARTIFACT_NAME
