# This is a shared workflow

name: compile and test one configuration

on:
  workflow_call:
    inputs:
      runs-on:
        description: operating system
        type: string
        required: true
      target:
        description: target to compile
        type: string
        required: true
      ruby:
        description: ruby version
        type: string
        required: true
      file-to-upload:
        description: dylib to upload
        type: string
        required: true
    outputs:
      artifact-name:
        description: artifact name
        value: ${{ jobs.compile-and-test-one.outputs.artifact-name }}

defaults:
  run:
    shell: bash

jobs:
  compile-and-test-one:
    name: compile and test on mac / ${{ inputs.ruby }}
    runs-on: ${{ inputs.runs-on }}
    env:
      TARGET: ${{ inputs.target }}
      OUTPUT_ARTIFACT_NAME: dylib-${{ inputs.target }}-${{ inputs.ruby }}
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby }}
          bundler-cache: true

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: compile and test
        run: make test

      - name: upload dylib
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.OUTPUT_ARTIFACT_NAME }}
          path: ${{ inputs.file-to-upload }}

      - name: output upload name
        id: upload
        run: echo ::set-output name=artifact-name::$OUTPUT_ARTIFACT_NAME
