name: doc

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: deploy doc on GitHub Pages
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
          bundler-cache: true

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: codegen
        run: make do-codegen

      - name: generate documentation
        run: bundle exec yard

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
