name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.build.name }} (${{ matrix.ruby }} / ${{ matrix.build.os }})
    runs-on: ${{ matrix.build.os }}
    env:
      TARGET: ${{ matrix.build.target }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'
        build:
          # - name: test
          #   os: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
          #   run: make test

          # - name: test
          #   os: macos-latest
          #   target: x86_64-apple-darwin
          #   run: make test

          # - os: windows-latest
          #   name: test
          #   target: x86_64-pc-windows-gnu
          #   run: make test

          - os: ubuntu-latest
            name: test-asan
            target: x86_64-unknown-linux-gnu
            run: |
              export LSAN_OPTIONS=suppressions=LSan.supp
              export ASAN_OPTIONS=detect_leaks=1

              # make sure our supression list includes everything from MRI
              # ruby -e 'p 42'

              # compile .so with ASAN
              CFLAGS="-fsanitize=address" make lib/lib-ruby-parser/lib_ruby_parser_native.so

              make test

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: run tests
        shell: bash
        run: ${{ matrix.build.run }}
