name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: test ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          # - '2.6'
          # - '2.7'
          - '3.0'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      # - name: setup msvc on windows
      #   if: runner.os == 'Windows'
      #   uses: ilammy/msvc-dev-cmd@v1

      # - name: fix linker on windows
      #   if: runner.os == 'Windows'
      #   run: |
      #     rm "C:\\Program Files\\Git\\usr\\bin\\link.exe"
      #     which -a link.exe

      - name: install wget
        if: runner.os == 'Windows'
        shell: bash
        run: choco install wget --no-progress

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: run bundler
        shell: bash
        run: gem install bundler && bundle install

      - name: run tests
        shell: bash
        run: |
          make download-c-bindings
          make generate-ruby-bindings
          make test
